name = ['Miya', 'Madiha', 'Brooklyn', 'Wanda', 'Shania', 'Alia', 'Haydn', 'Wilma', 'Susie', 'Carrie', 'Greta', 'Lilly-Rose', 'Michelle', 'Jade', 'Annabel', 'Isra', 'Asa', 'Gloria', 'Kaylee', 'Soraya', 'Alivia', 'Pamela', 'Leanne', 'Naomi', 'Natalia', 'Michaela', 'Erika', 'Carmen', 'Jane', 'Eve', 'Georgiana', 'Aamina', 'Sophia', 'Imogen', 'Ollie', 'Ann', 'Siena', 'Stephanie', 'Veronica', 'Nora', 'Edith', 'Macie', 'Billy', 'Priya', 'Molly', 'Zainab', 'Annie', 'Bethany', 'Eva', 'Kitty', 'Clara', 'Sadia', 'Candice', 'Tiana', 'Roseanna', 'Husna', 'Henrietta', 'Thea', 'Traci', 'Alison', 'Eileen', 'Skyla', 'Mathilda', 'Karina', 'Layla', 'Lula', 'Nikita', 'Eleanor', 
'Whitney', 'Leena', 'Tilly', 'Eleri', 'Scarlet', 'Jemma', 'Mabel', 'Lowri', 'Dulcie', 'Emma', 'Miriam', 'Bridget', 'Malaika', 'Zarah', 'Maggie', 'Valerie', 'Aishah', 'Tanya', 'Lachlan', 'Valentina', 'Marwa', 'Halima', 'Elif', 'Syeda', 'Charlie', 'Angela', 'Cordelia', 'Kasey', 'Willow', 'Anika', 'Jennifer', 'Sierra', 'Katherine', 'Cindy', 'Susan', 'Margaret', 'Michelle', 'Andrea', 'Heather', 'Denise', 'Rachel', 'Whitney', 'Michelle', 'Janice', 'Megan', 'Patty', 'Julia', 'Heather', 'Cheryl', 'Kayla', 'Jamie', 'Lisa', 'Sue', 'Kimberly', 'Monica', 'Jo', 'Penny', 'Amber', 'Erica', 'Gwendolyn', 'Lauren', 'Wanda', 'Christina', 'Misty', 'Jessica', 'Courtney', 
'Dominique', 'Sasha', 'Masha', 'Tanya', 'Sveta', 'Allison', 'Sarah', 'Carly', 'Susan', 'Beth', 'Michelle', 'Joann', 'Jasmine', 'Crystal', 'Teresa', 'Danielle', 'Janice', 'Natalie', 'Jo', 'Carla', 'Norma', 'Desiree', 'Kayla', 'Jennifer', 'Catherine', 'Diana', 'Miranda', 'Laura', 'Cheryl', 'Jamie', 'Crystal', 'Tara', 'Kathleen', 'April', 'Dawn', 'Hannah', 'Cynthia', 'Felicia', 'Krista', 'Zoe', 'Alyssa', 'Sydney', 'Michele', 'Heather', 'Vanessa', 'Kimberly', 'Amanda', 'Breanna', 'Cindy', 'Shannon', 'Jessica', 'Sandra', 'Haley', 'Amanda', 'Megan', 'Jessica', 'Christie', 'Brooke', 'Tammy', 'Leslie', 'Kaitlyn', 'Debra', 'Ashley', 'Amy']

surename = ['Cotton', 'Alexander', 'Little', 'Sutherland', 'Clay', 'Perry', 'Daniels', 'Pacheco', 'Mckenzie', 'Mason', 'Ho', 'Navarro', 'Schultz', 'Cummings', 'Prince', 'Brock', 'Gates', 'Potter', 'Ayers', 'Stewart', 'Freeman', 'Andrews', 'Mcclain', 'Blake', 'Harper', 'Mcintyre', 'Rivas', 'Ramsey', 'Michael', 'Huber', 'Bray', 'Aguilar', 'Barton', 'Carroll', 'Dennis', 'Andrade', 'Bartlett', 'Shaw', 'Craig', 'Hanson', 'Finley', 'Reese', 'Cannon', 'Burns', 'Melton', 'Patton', 'Shields', 'Hurst', 'Cervantes', 'Santiago', 'Robbins', 'Hart', 'Clements', 'Gaines', 'Huff', 'Harvey', 'Haley', 'Wilson', 'Mclean', 'Henry', 'Callahan', 'Trujillo', 'Kline', 'Irwin', 'Meyer', 
'Stephenson', 'Brady', 'Dunlap', 'Aguirre', 'Roberts', 'Peck', 'Escobar', 'Brewer', 'Mathews', 'Silva', 'Saunders', 'Mcdonald', 'Ford', 'Gardner', 'Rojas', 'Smith', 'Gamble', 'Malone', 'Odom', 'Kane', 'Reyes', 'Wade', 'Long', 'Ballard', 'Alvarado', 'Perkins', 'Slater', 'Hale', 'Levy', 'Barnett', 'Frederick', 'Manning', 'Newman', 'Harris', 'Wright', 'King', 'Taylor', 'Roberson', 'Brown', 'Miller', 'Smith', 'Prince', 'Marshall', 'Velasquez', 'Brown', 'Morse', 'Cummings', 'Castro', 'Carter', 'Aguilar', 'Diaz', 'Wilson', 'Williams', 'Collier', 'Aguilar', 'Porter', 'Mendoza', 'Cantrell', 'Harris', 'Young', 'Andrade', 'Carpenter', 'Solomon', 'Hoffman', 'Bryan', 'Huber', 'Green', 'Moore', 'Salinas', 'Duncan', 'Stephens', 'Daniels', 'Greer', 'Thompson', 'Garcia', 'Ayala', 'Pope', 'Carter', 'Frederick', 'Nelson', 'Roberts', 'Edwards', 'Huber', 'Fuller', 'Martin', 'Mayo', 'Jackson', 'Roman', 'Rodriguez', 'Smith', 'Harrison', 'Erickson', 'Carroll', 'Steele', 'Pruitt', 'Wells', 'Nunez', 'Lewis', 'Wilson', 'Harris', 'Scott', 'Graham', 'Greene', 'Lee', 'Smith', 'Downs', 'Soto', 'Jones', 'Taylor', 
'Rogers', 'Wiley', 'Mitchell', 'Suma', 'Galun', 'Mela', "Pochina", 'Zalaya', 'Patregkin', 'Pruitt', 'Smith', 'Cortez', 'Pham', 'Wilson', 'Mccoy', 'Rocha', 'Porter', 'Hernandez', 'Patel', 'Price', 'Davis', 'Roach', 'White', 'Young', 'Jones', 'Anderson']


screen_resolution = ["1024_600", "1366_1080", '1024_768',  "1280_720", '960_680']

ua = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36',
    # 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' # Мой юа 
    # 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15',
    # 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36',
    # 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15',
    # 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'
    ]