name = ['Miya', 'Madiha', 'Brooklyn', 'Wanda', 'Shania', 'Alia', 'Haydn', 'Wilma', 'Susie', 'Carrie', 'Greta', 'Lilly-Rose', 'Michelle', 'Jade', 'Annabel', 'Isra', 'Asa', 'Gloria', 'Kaylee', 'Soraya', 'Alivia', 'Pamela', 'Leanne', 'Naomi', 'Natalia', 'Michaela', 'Erika', 'Carmen', 'Jane', 'Eve', 'Georgiana', 'Aamina', 'Sophia', 'Imogen', 'Ollie', 'Ann', 'Siena', 'Stephanie', 'Veronica', 'Nora', 'Edith', 'Macie', 'Billy', 'Priya', 'Molly', 'Zainab', 'Annie', 'Bethany', 'Eva', 'Kitty', 'Clara', 'Sadia', 'Candice', 'Tiana', 'Roseanna', 'Husna', 'Henrietta', 'Thea', 'Traci', 'Alison', 'Eileen', 'Skyla', 'Mathilda', 'Karina', 'Layla', 'Lula', 'Nikita', 'Eleanor', 
'Whitney', 'Leena', 'Tilly', 'Eleri', 'Scarlet', 'Jemma', 'Mabel', 'Lowri', 'Dulcie', 'Emma', 'Miriam', 'Bridget', 'Malaika', 'Zarah', 'Maggie', 'Valerie', 'Aishah', 'Tanya', 'Lachlan', 'Valentina', 'Marwa', 'Halima', 'Elif', 'Syeda', 'Charlie', 'Angela', 'Cordelia', 'Kasey', 'Willow', 'Anika', 'Jennifer', 'Sierra', 'Katherine', 'Cindy', 'Susan', 'Margaret', 'Michelle', 'Andrea', 'Heather', 'Denise', 'Rachel', 'Whitney', 'Michelle', 'Janice', 'Megan', 'Patty', 'Julia', 'Heather', 'Cheryl', 'Kayla', 'Jamie', 'Lisa', 'Sue', 'Kimberly', 'Monica', 'Jo', 'Penny', 'Amber', 'Erica', 'Gwendolyn', 'Lauren', 'Wanda', 'Christina', 'Misty', 'Jessica', 'Courtney', 
'Dominique', 'Sasha', 'Masha', 'Tanya', 'Sveta', 'Allison', 'Sarah', 'Carly', 'Susan', 'Beth', 'Michelle', 'Joann', 'Jasmine', 'Crystal', 'Teresa', 'Danielle', 'Janice', 'Natalie', 'Jo', 'Carla', 'Norma', 'Desiree', 'Kayla', 'Jennifer', 'Catherine', 'Diana', 'Miranda', 'Laura', 'Cheryl', 'Jamie', 'Crystal', 'Tara', 'Kathleen', 'April', 'Dawn', 'Hannah', 'Cynthia', 'Felicia', 'Krista', 'Zoe', 'Alyssa', 'Sydney', 'Michele', 'Heather', 'Vanessa', 'Kimberly', 'Amanda', 'Breanna', 'Cindy', 'Shannon', 'Jessica', 'Sandra', 'Haley', 'Amanda', 'Megan', 'Jessica', 'Christie', 'Brooke', 'Tammy', 'Leslie', 'Kaitlyn', 'Debra', 'Ashley', 'Amy',
"Raya","Wrenley","Angelique","Vida","Emberlynn","Flora","Murphy","Arleth","Oakleigh","Freyja","Mylah","Taytum","Elia","Jaylani","Zayla","Navy","Della","Clover","Nyra",
"Olivia","Emma","Charlotte","Amelia","Ava","Sophia","Isabella","Mia","Evelyn","Harper","Luna","Camila","Gianna","Elizabeth","Eleanor","Ella","Abigail","Sofia","Avery","Scarlett","Emily","Aria","Penelope","Chloe","Layla","Mila","Nora","Hazel","Madison","Ellie","Lily","Nova","Isla","Grace","Violet","Aurora","Riley","Zoey","Willow","Emilia","Stella","Zoe","Victoria","Hannah","Addison","Leah","Lucy","Eliana","Ivy","Everly","Lillian","Paisley","Elena","Naomi","Maya","Natalie","Kinsley","Delilah","Claire","Audrey","Aaliyah","Ruby","Brooklyn","Alice","Aubrey","Autumn","Leilani","Savannah","Valentina","Kennedy","Madelyn","Josephine","Bella","Skylar","Genesis","Sophie",
"Hailey","Sadie","Natalia","Quinn","Caroline","Allison","Gabriella","Anna","Serenity","Nevaeh","Cora","Ariana","Emery","Lydia","Jade","Sarah","Eva","Adeline","Madeline","Piper","Rylee","Athena","Peyton","Everleigh","Vivian","Clara","Raelynn","Liliana","Samantha","Maria","Iris","Ayla","Eloise","Lyla","Eliza","Hadley","Melody","Julia","Parker","Rose","Isabelle","Brielle","Adalynn","Arya","Eden","Remi","Mackenzie","Maeve","Margaret","Reagan","Charlie","Alaia","Melanie","Josie","Elliana","Cecilia","Mary","Daisy","Alina","Lucia","Ximena","Juniper","Kaylee","Magnolia","Summer","Adalyn","Sloane","Amara","Arianna","Isabel","Reese","Emersyn","Sienna","Kehlani","River",
"Freya","Valerie","Blakely","Genevieve","Esther","Valeria","Katherine","Kylie","Norah","Amaya","Bailey","Ember","Ryleigh","Georgia","Catalina","Emerson","Alexandra","Faith","Jasmine","Ariella","Ashley","Andrea","Millie","June","Khloe","Callie","Juliette","Sage","Ada","Anastasia","Olive","Alani","Brianna","Rosalie","Molly","Brynlee","Amy","Ruth","Aubree","Gemma","Taylor","Oakley","Margot","Arabella","Sara","Journee","Harmony","Blake","Alaina","Aspen","Noelle","Selena","Oaklynn","Morgan","Londyn","Zuri","Aliyah","Jordyn","Juliana","Finley","Presley","Zara","Leila","Marley","Sawyer","Amira","Lilly","London","Kimberly","Elsie","Ariel","Lila","Alana","Diana","Kamila",
"Nyla","Vera","Hope","Annie","Kaia","Myla","Alyssa","Angela","Ana","Lennon","Evangeline","Harlow","Rachel","Gracie","Rowan","Laila","Elise","Sutton","Lilah","Adelyn","Phoebe","Octavia","Sydney","Mariana","Wren","Lainey","Vanessa","Teagan","Kayla","Malia","Elaina","Saylor","Brooke","Lola","Miriam","Alayna","Adelaide","Daniela","Jane","Payton","Journey","Lilith","Delaney","Dakota","Mya","Charlee","Alivia","Annabelle","Kailani","Lucille","Trinity","Gia","Tatum","Raegan","Camille","Kaylani","Kali","Stevie","Maggie","Haven","Tessa","Daphne","Adaline","Hayden","Joanna","Jocelyn","Lena","Evie","Juliet","Fiona","Cataleya","Angelina","Leia","Paige","Julianna","Milani","Talia",
"Rebecca","Kendall","Harley","Lia","Phoenix","Dahlia","Logan","Camilla","Thea","Jayla","Brooklynn","Blair","Vivienne","Hallie","Madilyn","Mckenna","Evelynn","Ophelia","Celeste","Alayah","Winter","Catherine","Collins","Nina","Briella","Palmer","Noa","Mckenzie","Kiara","Amari","Adriana","Gracelynn","Lauren","Cali","Kalani","Aniyah","Nicole","Alexis","Mariah","Gabriela","Amina","Ariyah","Adelynn","Remington","Reign","Alaya","Alexandria","Willa","Avianna","Makayla","Gracelyn","Elle","Amiyah","Arielle","Elianna","Giselle","Brynn","Ainsley","Aitana","Charli","Demi","Makenna","Rosemary","Danna","Izabella","Lilliana","Melissa","Samara","Lana","Mabel","Everlee",
"Fatima","Leighton","Esme","Raelyn","Madeleine","Nayeli","Camryn","Kira","Annalise","Selah","Serena","Rylie","Celine","Laura","Brinley","Frances","Michelle","Heidi","Rory","Sabrina","Destiny","Gwendolyn","Alessandra","Poppy","Amora","Nylah","Luciana","Maisie","Miracle","Joy","Liana","Raven","Shiloh","Allie","Daleyza","Kate","Lyric","Alicia","Lexi","Addilyn","Anaya","Malani","Paislee","Elisa","Kayleigh","Azalea","Francesca","Jordan","Regina","Viviana","Aylin","Skye","Daniella","Makenzie","Veronica","Legacy","Maia","Ariah","Alessia","Carmen","Astrid","Maren","Helen","Felicity","Alexa","Danielle","Lorelei","Paris","Adelina","Bianca","Gabrielle","Jazlyn","Scarlet",
"Bristol","Esmeralda","Colette","Stephanie","Jolene","Marlee","Sarai","Hattie","Nadia","Rosie","Kamryn","Kenzie","Alora","Holly","Matilda","Sylvia","Cameron","Armani","Emelia","Keira","Braelynn","Jacqueline","Alison","Amanda","Cassidy","Emory","Ari","Haisley","Jimena","Jessica","Elaine","Dorothy","Mira","Eve","Oaklee","Averie","Charleigh","Lyra","Madelynn","Angel","Edith","Jennifer","Raya","Ryan","Heaven","Kyla","Wrenley","Meadow","Carter","Kora","Saige","Kinley","Maci","Mae","Salem","Aisha","Adley","Carolina","Sierra","Alma","Helena","Bonnie","Mylah","Briar","Aurelia","Leona","Macie","Maddison","April","Aviana","Lorelai","Alondra","Kennedi","Monroe","Emely","Maliyah",
"Ailani","Madilynn","Renata","Katie","Zariah","Imani","Amber","Analia","Ariya","Anya","Emberly","Emmy","Mara","Maryam","Dior","Mckinley","Virginia","Amalia","Mallory","Opal","Shelby","Clementine","Remy","Elliott","Elora","Katalina","Antonella","Skyler","Hanna","Kaliyah","Alanna","Haley","Itzel","Cecelia","Jayleen","Kensley","Beatrice","Journi","Dylan","Ivory","Yaretzi","Meredith","Sasha","Gloria","Oaklyn","Sloan","Abby","Davina","Lylah","Erin","Reyna","Kaitlyn","Michaela","Nia","Fernanda","Jaliyah","Jenna","Sylvie","Miranda","Anne","Mina","Myra","Aleena","Alia","Frankie","Ellis","Kathryn","Nalani","Nola","Jemma","Lennox","Marie","Angelica","Cassandra","Calliope","Adrianna",
]


surename = ['Cotton', 'Alexander', 'Little', 'Sutherland', 'Clay', 'Perry', 'Daniels', 'Pacheco', 'Mckenzie', 'Mason', 'Ho', 'Navarro', 'Schultz', 'Cummings', 'Prince', 'Brock', 'Gates', 'Potter', 'Ayers', 'Stewart', 'Freeman', 'Andrews', 'Mcclain', 'Blake', 'Harper', 'Mcintyre', 'Rivas', 'Ramsey', 'Michael', 'Huber', 'Bray', 'Aguilar', 'Barton', 'Carroll', 'Dennis', 'Andrade', 'Bartlett', 'Shaw', 'Craig', 'Hanson', 'Finley', 'Reese', 'Cannon', 'Burns', 'Melton', 'Patton', 'Shields', 'Hurst', 'Cervantes', 'Santiago', 'Robbins', 'Hart', 'Clements', 'Gaines', 'Huff', 'Harvey', 'Haley', 'Wilson', 'Mclean', 'Henry', 'Callahan', 'Trujillo', 'Kline', 'Irwin', 'Meyer', 
'Stephenson', 'Brady', 'Dunlap', 'Aguirre', 'Roberts', 'Peck', 'Escobar', 'Brewer', 'Mathews', 'Silva', 'Saunders', 'Mcdonald', 'Ford', 'Gardner', 'Rojas', 'Smith', 'Gamble', 'Malone', 'Odom', 'Kane', 'Reyes', 'Wade', 'Long', 'Ballard', 'Alvarado', 'Perkins', 'Slater', 'Hale', 'Levy', 'Barnett', 'Frederick', 'Manning', 'Newman', 'Harris', 'Wright', 'King', 'Taylor', 'Roberson', 'Brown', 'Miller', 'Smith', 'Prince', 'Marshall', 'Velasquez', 'Brown', 'Morse', 'Cummings', 'Castro', 'Carter', 'Aguilar', 'Diaz', 'Wilson', 'Williams', 'Collier', 'Aguilar', 'Porter', 'Mendoza', 'Cantrell', 'Harris', 'Young', 'Andrade', 'Carpenter', 'Solomon', 'Hoffman', 'Bryan', 'Huber', 'Green', 'Moore', 'Salinas', 'Duncan', 'Stephens', 'Daniels', 'Greer', 'Thompson', 'Garcia', 'Ayala', 'Pope', 'Carter', 'Frederick', 'Nelson', 'Roberts', 'Edwards', 'Huber', 'Fuller', 'Martin', 'Mayo', 'Jackson', 'Roman', 'Rodriguez', 'Smith', 'Harrison', 'Erickson', 'Carroll', 'Steele', 'Pruitt', 'Wells', 'Nunez', 'Lewis', 'Wilson', 'Harris', 'Scott', 'Graham', 'Greene', 'Lee', 'Smith', 'Downs', 'Soto', 'Jones', 'Taylor', 
'Rogers', 'Wiley', 'Mitchell', 'Suma', 'Galun', 'Mela', "Pochina", 'Zalaya', 'Patregkin', 'Pruitt', 'Smith', 'Cortez', 'Pham', 'Wilson', 'Mccoy', 'Rocha', 'Porter', 'Hernandez', 'Patel', 'Price', 'Davis', 'Roach', 'White', 'Young', 'Jones', 'Anderson']


screen_resolution = ["1280_720"]  # "1024_600", "1366_1080", '1024_768',  

ua = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36'
    # 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' # Мой юа 
    # 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15',
    # 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36',
    # 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15',
    # 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'
    ]

